### ISSUE TITLE
Improve Dark Mode

### ISSUE THREAD

**Issue by userzzzq** [mifi/lossless-cut#1969]
### The fewer issues I have to read, the more new features I will have time to implement, so I ask that you please try these things first

- [X] Check out all the menus and keyboard shortcuts. Maybe the feature already exists?
- [X] Try with the [newest version from GitHub](https://github.com/mifi/lossless-cut/releases/latest)
- [X] Read the [documentation](https://github.com/mifi/lossless-cut) and [FAQ, Known issues, Troubleshooting](https://github.com/mifi/lossless-cut/blob/master/issues.md) to see if the feature already exists
- [X] See if someone already suggested this under [Issues](https://github.com/mifi/lossless-cut/issues) or [Discussions](https://github.com/mifi/lossless-cut/discussions)

### Description

some UI still use white background, such as the Merge Files page, the scrollbar of "batch files" pannel (at left).
please improve the dark mode.

**Comment by mifi** [comment]
related #733

**Comment by XCanG** [comment]
@mifi I have a little suggestion: add style [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)

You can use `color-scheme: light dark;` to support both themes, even right now it would improve scroll bars, an example if you add this to `html` element styles via devtools:
* Default styles:
  ![2024-05-14_19-30-24_LosslessCut](https://github.com/mifi/lossless-cut/assets/4011523/2261c315-5f2a-4187-9c2b-b09db0302442)
* With `color-scheme` and dark system theme:
  ![2024-05-14_19-30-51](https://github.com/mifi/lossless-cut/assets/4011523/7425b3dd-d5d7-46b9-84cb-eaf2aee48f3a)

Another screen example:
* Default:
  ![2024-05-14_19-31-15_LosslessCut](https://github.com/mifi/lossless-cut/assets/4011523/5e929f5f-eef3-4ec0-a2a7-523e4a4b6040)
* With:
  ![2024-05-14_19-31-41_LosslessCut](https://github.com/mifi/lossless-cut/assets/4011523/a66f424a-02df-4c0e-877f-9e209f6ceddb)


Additionally there is [`light-dark()` function](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) that will allow you to style freely between both themes, like that:
```css
.selector {
    background-color: light-dark(var(--light-background), var(--dark-background));
    color: light-dark(var(--light-text), var(--dark-text));
}
```

Currently lossless-cut use Chrome version **118**, so it is not supported.
![image](https://github.com/mifi/lossless-cut/assets/4011523/db7ac908-9eff-4ad9-8627-0d45db464253)

But if you upgrade Electron with a Chrome version **123** or newer, you can easily use it.

**Comment by XCanG** [comment]
Well, it is also possible to manually restyle scrollbars with CSS instead of relying on color-scheme like that (Chrome-only):
```css
*::-webkit-scrollbar {
	width: 8px;
	height: 8px;
	background-color: transparent;
}

*::-webkit-scrollbar-thumb {
	background-color: #8888;
}

*::-webkit-scrollbar:hover {
	background-color: #8883;
}
```
